--- #YAML:1.0
name:               Arepa
version:            0.85
abstract:           Apt REPository Assistant
author:
    - Esteban Manchado Velázquez <estebanm@opera.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::Tiny:         0
    DBD::SQLite:          0
    File::chmod:          0
    HTML::Tree:           0
    Mojolicious:          0
    MojoX::Session:       0
    Parse::Debian::PackageDesc:  0
    Test::Class:          0
    Test::Deep:           0
    XML::RSS:             0
    YAML::Syck:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
